name: Example workflow using Snyk
on: [push, pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Print environment variables for debugging
      #- name: Debug Environment Variables
      #  run: |
      #    echo "Printing environment variables:"
      #    env

      # Step 4: Run Snyk with debug enabled
      #- name: Run Snyk to check for vulnerabilities (with debug)
      #  uses: snyk/actions/node@master
      #  continue-on-error: true
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #    args: --severity-threshold=critical --json 
      
      # Step 4: Run Snyk in the shell so we can redirect output
      - name: Run Snyk test and save results
        run: |
          snyk test --severity-threshold=critical --json > snyk.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 5: Run python script in runner vm using environment variables
      - name: Create GitHub Issue if Vulnerabilities Found
        run: python3 create_issue.py critical
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      
