name: Snyk Test on push to main
on:
  push:
    branches: [ main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Run Snyk test with critical severity filter
      - name: Run Snyk to check for vulnerabilities output as json
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          #args: --severity-threshold=critical
          json: true
      
      # Step 3: Run python script in runner vm with github vars/secrets as env vars
      # Script takes critical,high,medium,low as comma seperated inputs
      - name: Create GitHub Issue filtered by severity
        run: python3 create_issue.py medium,high
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      
