name: Snyk Test on push to main
on:
  push:
    branches: [ main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Print environment variables for debugging
      #- name: Debug Environment Variables
      #  run: |
      #    echo "Printing environment variables:"
      #    env

      # Step 4: Run Snyk with debug enabled
      - name: Run Snyk to check for vulnerabilities (with debug)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low
          json: true
      
      # Step 5: Run python script in runner vm using environment variables
      - name: Create GitHub Issue if Vulnerabilities Found
        run: python3 create_issue.py critical,high
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      
